"""
BotGeek - Report Agent
Generates professional security audit reports in HTML and plain text.
"""

import os
import logging
from datetime import datetime
from dataclasses import dataclass
from typing import Optional, List

logger = logging.getLogger("botgeek.agents.report")


@dataclass
class AuditData:
    target: str
    recon: Optional[object] = None
    scan: Optional[object] = None
    vuln: Optional[object] = None
    web: Optional[object] = None
    wifi: Optional[object] = None
    ml_scores: Optional[list] = None
    timestamp: str = ""

    def __post_init__(self):
        self.timestamp = self.timestamp or datetime.now().strftime("%Y-%m-%d %H:%M:%S")


class ReportAgent:
    """Generates structured HTML + TXT security reports."""

    OUTPUT_DIR = "/tmp/botgeek_reports"

    def __init__(self):
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)

    def generate(self, data: AuditData) -> dict:
        slug = data.target.replace("/", "_").replace(":", "_")
        ts   = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = f"{self.OUTPUT_DIR}/botgeek_{slug}_{ts}"

        txt_path  = self._write_txt(data, base + ".txt")
        html_path = self._write_html(data, base + ".html")

        logger.info(f"[Report] TXT  → {txt_path}")
        logger.info(f"[Report] HTML → {html_path}")

        return {"txt": txt_path, "html": html_path}

    # ------------------------------------------------------------------  TXT

    def _write_txt(self, d: AuditData, path: str) -> str:
        lines = [
            "=" * 70,
            "  BotGeek Security Audit Report",
            f"  Target   : {d.target}",
            f"  Date     : {d.timestamp}",
            "=" * 70,
        ]

        if d.recon:
            lines += ["", "[1] RECON", "-" * 40]
            if d.recon.whois:
                lines.append(d.recon.whois[:600])
            if d.recon.subdomains:
                lines.append(f"Subdomains: {', '.join(d.recon.subdomains[:10])}")
            if d.recon.emails:
                lines.append(f"Emails: {', '.join(d.recon.emails[:10])}")

        if d.scan:
            lines += ["", "[2] SCAN RESULTS", "-" * 40]
            for p in d.scan.open_ports:
                lines.append(f"  {p.port:5d}/{p.protocol}  {p.service:15s}  {p.version}")
            if d.scan.os_guess:
                lines.append(f"  OS: {d.scan.os_guess}")

        if d.vuln:
            lines += ["", "[3] VULNERABILITIES", "-" * 40]
            lines.append(f"  Risk Score: {d.vuln.risk_score}/10")
            for v in d.vuln.vulnerabilities:
                lines.append(
                    f"  [{v.severity}] {v.cve_id} — {v.service} {v.version}"
                )
                lines.append(f"    {v.description}")
                if v.exploit_available:
                    lines.append("    ⚠  Public exploit available")
                lines.append(f"    ✔  Remediation: {v.remediation}")

        if d.ml_scores:
            lines += ["", "[4] ML EXPLOIT PREDICTION", "-" * 40]
            for s in d.ml_scores:
                pct = int(s.exploit_probability * 100)
                lines.append(
                    f"  {s.service:15s}  prob={pct}%  tier={s.risk_tier}"
                )
                lines.append(f"    Factors: {', '.join(s.factors)}")

        if d.web:
            lines += ["", "[5] WEB APPLICATION", "-" * 40]
            for f in d.web.findings[:10]:
                lines.append(f"  [{f.severity}] {f.description[:120]}")
            if d.web.directories:
                lines.append(f"  Directories found: {len(d.web.directories)}")

        lines += [
            "",
            "[6] RECOMMENDATIONS",
            "-" * 40,
            *self._recommendations(d),
            "",
            "=" * 70,
            "  Report generated by BotGeek AI Security Platform",
            "=" * 70,
        ]

        content = "\n".join(lines)
        with open(path, "w") as f:
            f.write(content)
        return path

    # ------------------------------------------------------------------  HTML

    def _write_html(self, d: AuditData, path: str) -> str:
        recs = self._recommendations(d)
        rec_html = "".join(f"<li>{r}</li>" for r in recs)

        port_rows = ""
        if d.scan:
            for p in d.scan.open_ports:
                port_rows += (
                    f"<tr><td>{p.port}/{p.protocol}</td>"
                    f"<td>{p.service}</td><td>{p.version}</td></tr>"
                )

        vuln_rows = ""
        if d.vuln:
            for v in d.vuln.vulnerabilities:
                cls = v.severity.lower()
                exp = "⚠ YES" if v.exploit_available else "–"
                vuln_rows += (
                    f"<tr class='sev-{cls}'>"
                    f"<td><span class='badge {cls}'>{v.severity}</span></td>"
                    f"<td>{v.cve_id}</td>"
                    f"<td>{v.service} {v.version}</td>"
                    f"<td>{v.description[:150]}</td>"
                    f"<td>{exp}</td>"
                    f"<td>{v.remediation}</td></tr>"
                )

        ml_rows = ""
        if d.ml_scores:
            for s in d.ml_scores:
                pct = int(s.exploit_probability * 100)
                ml_rows += (
                    f"<tr><td>{s.service}</td>"
                    f"<td><div class='bar-wrap'>"
                    f"<div class='bar' style='width:{pct}%'>{pct}%</div>"
                    f"</div></td>"
                    f"<td><span class='badge {s.risk_tier.lower()}'>{s.risk_tier}</span></td>"
                    f"<td>{', '.join(s.factors[:3])}</td></tr>"
                )

        risk = d.vuln.risk_score if d.vuln else 0
        risk_color = (
            "#e74c3c" if risk >= 7 else
            "#e67e22" if risk >= 4 else
            "#2ecc71"
        )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>BotGeek Report — {d.target}</title>
<style>
  :root{{--bg:#0d1117;--panel:#161b22;--border:#30363d;--text:#c9d1d9;--accent:#58a6ff;
         --critical:#ff4747;--high:#ff8c00;--medium:#ffd700;--low:#2ecc71;--info:#58a6ff}}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Courier New',monospace;background:var(--bg);color:var(--text);padding:30px}}
  h1{{color:var(--accent);font-size:2rem;margin-bottom:4px}}
  .meta{{color:#8b949e;margin-bottom:30px;font-size:.85rem}}
  .grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin-bottom:30px}}
  .card{{background:var(--panel);border:1px solid var(--border);border-radius:8px;padding:20px}}
  .card h3{{color:#8b949e;font-size:.75rem;text-transform:uppercase;letter-spacing:1px;margin-bottom:8px}}
  .card .val{{font-size:2rem;font-weight:bold}}
  .section{{background:var(--panel);border:1px solid var(--border);border-radius:8px;
             padding:24px;margin-bottom:20px}}
  .section h2{{color:var(--accent);margin-bottom:16px;font-size:1rem;
               text-transform:uppercase;letter-spacing:2px}}
  table{{width:100%;border-collapse:collapse;font-size:.85rem}}
  th{{text-align:left;color:#8b949e;padding:8px 12px;border-bottom:1px solid var(--border)}}
  td{{padding:8px 12px;border-bottom:1px solid #21262d;vertical-align:top}}
  tr:hover td{{background:#1c2128}}
  .badge{{padding:2px 8px;border-radius:4px;font-size:.75rem;font-weight:bold}}
  .critical,.badge.critical{{background:#3d0000;color:var(--critical);border:1px solid var(--critical)}}
  .high,.badge.high{{background:#2d1a00;color:var(--high);border:1px solid var(--high)}}
  .medium,.badge.medium{{background:#2d2700;color:var(--medium);border:1px solid var(--medium)}}
  .low,.badge.low{{background:#002d11;color:var(--low);border:1px solid var(--low)}}
  .info,.badge.info{{background:#001a2d;color:var(--info);border:1px solid var(--info)}}
  .risk-score{{font-size:3rem;font-weight:bold;color:{risk_color}}}
  .bar-wrap{{background:#21262d;border-radius:4px;height:20px;min-width:120px}}
  .bar{{height:100%;background:var(--accent);border-radius:4px;
        display:flex;align-items:center;padding-left:6px;font-size:.75rem;
        font-weight:bold;color:#000;min-width:30px}}
  ul{{padding-left:20px}}
  li{{margin-bottom:6px;font-size:.9rem}}
  footer{{text-align:center;color:#8b949e;font-size:.75rem;margin-top:40px}}
</style>
</head>
<body>

<h1>⚡ BotGeek Security Report</h1>
<p class="meta">Target: <strong>{d.target}</strong> &nbsp;|&nbsp; Generated: {d.timestamp}</p>

<div class="grid">
  <div class="card">
    <h3>Open Ports</h3>
    <div class="val" style="color:var(--accent)">{len(d.scan.open_ports) if d.scan else 0}</div>
  </div>
  <div class="card">
    <h3>Vulnerabilities</h3>
    <div class="val" style="color:var(--critical)">{len(d.vuln.vulnerabilities) if d.vuln else 0}</div>
  </div>
  <div class="card">
    <h3>Risk Score</h3>
    <div class="val risk-score">{risk}/10</div>
  </div>
  <div class="card">
    <h3>OS Detected</h3>
    <div class="val" style="font-size:1rem;margin-top:8px">{d.scan.os_guess if d.scan and d.scan.os_guess else "–"}</div>
  </div>
</div>

{'<div class="section"><h2>Open Ports & Services</h2><table><tr><th>Port</th><th>Service</th><th>Version</th></tr>' + port_rows + '</table></div>' if port_rows else ''}

{'<div class="section"><h2>Vulnerability Analysis</h2><table><tr><th>Severity</th><th>CVE</th><th>Service</th><th>Description</th><th>Exploit</th><th>Fix</th></tr>' + vuln_rows + '</table></div>' if vuln_rows else ''}

{'<div class="section"><h2>ML Exploit Prediction</h2><table><tr><th>Service</th><th>Probability</th><th>Risk</th><th>Key Factors</th></tr>' + ml_rows + '</table></div>' if ml_rows else ''}

<div class="section">
  <h2>Recommendations</h2>
  <ul>{rec_html}</ul>
</div>

<footer>BotGeek AI Security Platform — Lab Use Only</footer>
</body></html>"""

        with open(path, "w") as f:
            f.write(html)
        return path

    # ------------------------------------------------------------------

    def _recommendations(self, d: AuditData) -> list:
        recs = []
        if d.scan:
            for p in d.scan.open_ports:
                if p.port in (23, 21):
                    recs.append(f"Disable {p.service} (port {p.port}) — use SSH/SFTP instead")
                if p.port == 445:
                    recs.append("Disable SMBv1, apply MS17-010 patch")
        if d.vuln:
            for v in d.vuln.vulnerabilities:
                if v.exploit_available and v.remediation:
                    recs.append(f"[{v.cve_id}] {v.remediation}")
        if not recs:
            recs.append("No critical issues detected — continue regular audits")
        recs.append("Enforce firewall rules to restrict unnecessary open ports")
        recs.append("Keep all services updated to latest stable versions")
        return list(dict.fromkeys(recs))  # deduplicate preserving order
